# Generated by Django 4.2.5 on 2024-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='cuisineType',
            field=models.CharField(choices=[('Thakali', 'Thakali'), ('Newari', 'Newari'), ('Sherpa', 'Sherpa'), ('Tamang', 'Tamang'), ('Nepali ', 'Nepali')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='recipeIngredient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='recipeSteps',
            field=models.TextField(blank=True),
        ),
    ]
