# Generated by Django 4.2.5 on 2024-04-09 13:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_addrecipe_recipeproducttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecipe',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=0.00021958717610891522),
            preserve_default=False,
        ),
    ]
