# Generated by Django 4.2.5 on 2024-04-09 13:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_addrecipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
