# Generated by Django 4.2.7 on 2023-11-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilepicture',
            name='user',
        ),
        migrations.DeleteModel(
            name='userDocument',
        ),
        migrations.DeleteModel(
            name='userProfilePicture',
        ),
    ]
