# Generated by Django 4.2.7 on 2023-11-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofilepicture_user_delete_userdocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='contact_number',
            new_name='contactNumber',
        ),
    ]
