# Generated by Django 4.2.5 on 2023-12-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdocument',
            old_name='image',
            new_name='documentImage',
        ),
        migrations.RenameField(
            model_name='userprofilepicture',
            old_name='image',
            new_name='profileImage',
        ),
    ]
