# Generated by Django 4.2.5 on 2023-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_image_userdocument_documentimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='requestedGroup',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
