# Generated by Django 4.2.5 on 2024-01-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersdetail_requestedgroup_alter_usersdetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='requestedGroup',
            field=models.CharField(max_length=50),
        ),
    ]
