# Generated by Django 4.2.5 on 2024-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersdetail_requestedgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
