# Generated by Django 4.2.5 on 2024-02-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usersdetail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='requestedGroup',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
