# Generated by Django 4.2.5 on 2024-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usersdetail_requestedgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='requestedGroup',
            field=models.CharField(max_length=50),
        ),
    ]
