# Generated by Django 4.2.5 on 2024-02-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usersdetail_requestedgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='requestedGroup',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
