# Generated by Django 4.2.5 on 2024-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usersdetail_requestedgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
