# Generated by Django 4.2.5 on 2024-02-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producTitle', models.CharField(max_length=100)),
                ('producBrand', models.CharField(max_length=100)),
                ('productDescription', models.TextField()),
                ('productCategory', models.CharField(choices=[('spicesFood', 'SpicesFood'), ('pansPots', 'PansPots'), ('knifes', 'knifes'), ('electricAppliance', 'electricAppliance'), ('cleaningAppliance', 'cleaningAppliance')], default='spicesFood', max_length=20)),
                ('productTag', models.CharField(choices=[('spice', 'spice'), ('pots', 'pots'), ('knifes', 'knifes'), ('appliance', 'appliance')], default='spice', max_length=20)),
                ('productImage', models.ImageField(upload_to='images/marketplace/productImage/')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productStock', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
