# Generated by Django 4.2.5 on 2024-02-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproducts',
            old_name='producTitle',
            new_name='productName',
        ),
    ]
