# Generated by Django 4.2.5 on 2024-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_productitle_addproducts_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproducts',
            name='productCategory',
        ),
        migrations.AlterField(
            model_name='addproducts',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/marketplace/productImage/'),
        ),
        migrations.AddField(
            model_name='addproducts',
            name='productCategory',
            field=models.ManyToManyField(default='spicesFood', to='market.addproducts'),
        ),
    ]
