# Generated by Django 4.2.5 on 2024-02-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_addproducts_productcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproducts',
            old_name='producBrand',
            new_name='productBrand',
        ),
    ]
