# Generated by Django 4.2.5 on 2024-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_producbrand_addproducts_productbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='productCategory',
            field=models.ManyToManyField(choices=[('spicesFood', 'SpicesFood'), ('pansPots', 'PansPots'), ('knifes', 'knifes'), ('electricAppliance', 'electricAppliance'), ('cleaningAppliance', 'cleaningAppliance')], default='spicesFood', to='market.addproducts'),
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='productTag',
        ),
        migrations.AddField(
            model_name='addproducts',
            name='productTag',
            field=models.ManyToManyField(choices=[('spice', 'spice'), ('pots', 'pots'), ('knifes', 'knifes'), ('appliance', 'appliance')], to='market.addproducts'),
        ),
    ]
