# Generated by Django 4.2.5 on 2024-02-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_addproducts_productcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproducts',
            name='productTag',
        ),
    ]
