# Generated by Django 4.2.5 on 2024-02-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_addproducts_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='productCategory',
            field=models.ManyToManyField(choices=[('spicesFood', 'SpicesFood'), ('pansPots', 'PansPots'), ('knifes', 'knifes'), ('electricAppliance', 'electricAppliance'), ('cleaningAppliance', 'cleaningAppliance')], default=[], to='market.addproducts'),
        ),
    ]
