# Generated by Django 4.2.5 on 2024-02-28 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_addproducts_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproducts',
            name='productCategory',
        ),
        migrations.AddField(
            model_name='addproducts',
            name='productCategory',
            field=models.CharField(choices=[('spicesFood', 'SpicesFood'), ('pansPots', 'PansPots'), ('knifes', 'knifes'), ('electricAppliance', 'electricAppliance'), ('cleaningAppliance', 'cleaningAppliance')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
