# Generated by Django 4.2.5 on 2024-02-29 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_addproducts_productcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproducts',
            name='productImage',
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/marketplace/productImage/')),
                ('addProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.addproducts')),
            ],
        ),
    ]
