# Generated by Django 4.2.5 on 2024-02-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_addproducts_productimage_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='addProducts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.addproducts'),
        ),
    ]
