# Generated by Django 4.2.5 on 2024-03-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
