# Generated by Django 4.2.5 on 2024-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='rating',
            field=models.FloatField(default=5.928853754940711e-05),
            preserve_default=False,
        ),
    ]
