# Generated by Django 4.2.5 on 2024-03-28 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=5.293619424054206e-05, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=5.293619424054206e-05),
            preserve_default=False,
        ),
    ]
