# Generated by Django 4.2.5 on 2024-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_order_buy_date_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='new_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='new_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_address',
            field=models.CharField(default=5.293619424054206e-05, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_number',
            field=models.CharField(default=5.293619424054206e-05, max_length=10),
            preserve_default=False,
        ),
    ]
