# Generated by Django 4.2.5 on 2024-03-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_remove_order_amount_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
