# Generated by Django 4.2.5 on 2024-03-31 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0026_rename_ordered_number_order_ordered_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='seller',
            field=models.ForeignKey(default=4.7813336733392836e-05, on_delete=django.db.models.deletion.CASCADE, related_name='seller_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
