# Generated by Django 4.2.5 on 2024-03-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_cartitem_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='seller',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='seller_cart',
            field=models.ForeignKey(default=4.7813336733392836e-05, on_delete=django.db.models.deletion.CASCADE, related_name='seller_cart_items', to='market.addproducts'),
            preserve_default=False,
        ),
    ]
