# Generated by Django 4.2.5 on 2024-03-31 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0029_remove_cartitem_seller_cart_cartitem_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
