# Generated by Django 4.2.5 on 2024-04-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_rename_order_orderdetail_order_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_for',
            new_name='order',
        ),
    ]
