# Generated by Django 4.2.5 on 2024-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_rename_order_for_orderdetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='order_for',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_each_product',
            field=models.DecimalField(decimal_places=2, default=0.001976284584980237, max_digits=10),
            preserve_default=False,
        ),
    ]
