# Generated by Django 4.2.5 on 2024-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_rename_order_orderdetail_order_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_completed',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
