# Generated by Django 4.2.5 on 2024-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_remove_order_is_completed_orderdetail_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='is_completed',
            field=models.CharField(choices=[('Shipping Canceled', 'Shipping Canceled'), ('Shipping Completed', 'Shipping Completed'), ('Shipping Pending', 'Shipping Pending')], default='Shipping Pending', max_length=120),
        ),
    ]
