# Generated by Django 4.2.5 on 2024-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_alter_orderdetail_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
