# Generated by Django 6.0.2 on 2026-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_orderdetail_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_type',
            field=models.CharField(choices=[('Online Payment', 'Online Payment'), ('Cash on Delivery', 'Cash on Delivery')], max_length=120),
        ),
    ]
