# Generated by Django 4.2.5 on 2024-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
