# Generated by Django 4.2.5 on 2024-03-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_addrestaurant_restaurantimage_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='latitude',
            new_name='latitudesearch',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='longitude',
            new_name='longitudesearh',
        ),
    ]
