# Generated by Django 4.2.5 on 2024-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_rename_latitude_search_latitudesearch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='restaurantImage/'),
        ),
    ]
