# Generated by Django 4.2.5 on 2024-03-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_addrecipe_restaurantimage_addrestaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
