# Generated by Django 4.2.5 on 2024-03-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_restaurantfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantfeedback',
            old_name='product',
            new_name='restaurant',
        ),
    ]
