# Generated by Django 4.2.5 on 2024-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_addrestaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_addres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addrestaurant',
            name='restaurantType',
            field=models.CharField(choices=[('Thakali', 'Thakali'), ('Newari', 'Newari'), ('Newari', 'Sherpa'), ('Tamang', 'Tamang'), ('Nepali ', 'Nepali')], max_length=100),
        ),
    ]
